###user服务的端口号
server:
  port: 8002
###服务别名----服务注册到注册中心名称 
spring:
  application:
    ###服务名称(服务注册到zk上的名称)  
    name: consul-vip
  cloud:
    consul: 
    ##consul地址
      host: 127.0.0.1
      port: 8500
      ##默认情况下、生成的地址是pc-XXX
      discovery: 
        hostname: 192.168.50.66